version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: server
    command: npm run start:server
    restart: "no"
    volumes:
      - ./packages/server:/root/app/packages/server:ro
      - ./packages/shared:/root/app/packages/shared:ro
    ports:
      - 8001:8000
    env_file:
      - ./environment/.env.default
      - ./environment/.env.server

  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: mongodb
    env_file:
      - ./environment/.env.default
    restart: "no"
    ports:
      - 27019:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./data/mongodb:/bitnami/mongodb